services:
  jobs-db:
    container_name: jobs-db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data:
